### PR TITLE
Add Select Sync Document Menu

### PR DESCRIPTION
**Pull request by SatoruUeda**
A designer asked me for advice on downloading only specific pages and screens, as it takes a long time to download a large number of screens in Figma.

So we added a menu that allows you to select pages and screens to download.

We have changed the structure of the process.

We would appreciate it if you could close it if it seems that our response violates UnityFigmaBridge's design policy.
Please check.

### CODE REVIEW

**Comment by SatoruUeda** [comment]
The dialog will look like this

image

https://www.figma.com/file/DIhmjD8NcAF2UHf69y53fn/Figma-Unity-Bridge-Example?node-id=3%3A1288&t=FojAQsm2ZbnOJL9r-1

**Comment by simonoliver** [comment]
Hey, thanks for the contribution! I'm on holiday next week but will review when I get back in early May.

**Comment by SatoruUeda** [comment]
Thank you for checking!

> Page selection vs screen selection
> What do you think about just allowing Page Selection and not Screens? 
> It would be great to understand your use case for screen selection though - can you describe where you need screen selection as well as page selection?


In our project, we are going to create many screens.
If one screen is modified due to a change in specifications, we may want to download only that screen.
If new screens are added, we would like to download only those screens.

We prefer to be able to select pages because they may be used for notes or sketches.

> Optional page selection

I see what you mean!
That would be better. I will do so.

> Store selected pages
> A nice workflow would be

I think that's a good idea! I will do so.

> Missing component definitions

https://github.com/simonoliver/UnityFigmaBridge/pull/19/files#diff-ef44a177dc0a75e670d6ba839954b9411af1a025928ae44191fe10c5e 7381596R32

I am trying to make sure that the child is processed even on pages that do not download, so that screens that are not included on the page are also downloaded.
Similarly for components, I thought that all page components would be downloaded, is my understanding correct?

https://github.com/simonoliver/UnityFigmaBridge/pull/19/files#diff-ef44a177dc0a75e670d6ba839954b9411af1a025928ae44191fe10c5e 7381596R39

I believe that only the prefab of the page is not created here.

**Comment by simonoliver** [comment]
Thanks for the reply, I understand - so you would do a full sync for all screens first, then next time you would only select screens that you want to update?

I have a plan for optimising import that will help with this but is not implemented yet - the importer will load the last import JSON file (FigmaOutput.json) and will compare with the new downloaded document. It will mark which nodes have changed (and whose child node has changed) and it will only update pages, screens, server render images, components etc that have changed. This should make updates much faster - when this is implemented, will it address your use case for selecting screens?

**Comment by SatoruUeda** [comment]
> so you would do a full sync for all screens first, then next time you would only select screens that you want to update?

Yes, that is correct.

> when this is implemented, will it address your use case for selecting screens?

yes that's the ideal behavior

In the future, I think I will manually set the Animator  for the Screen prefab imported from Figma.
At that time, I thought it would be nice if I could prevent that prefab from being overwritten.

**Comment by SatoruUeda** [comment]
We have addressed the points you raised.
"Only import selected pages" item was added to UnityFigmaBridgeSettings.
Removed "Select Sync Document" menu item.
Save selected pages and screens to the UnityFigmaBridgeSettings file.
Notify users of any changes to the Figma site during Sync.

`https://github.com/simonoliver/UnityFigmaBridge/pull/19/files#diff-04a05bb17d1801eb0dda7b9f7fa625383d207ece1defa1a49fc67f9707cc 382eR120`
`https://github.com/simonoliver/UnityFigmaBridge/pull/19/files#diff-04a05bb17d1801eb0dda7b9f7fa625383d207ece1defa1a49fc67f9707cc 382eR133`
It was possible to determine whether to delete the prefab for Assets/Figma/Pages and Assets/Figma/Screens only by name, so that is what I did.
Please let me know if there is any proper way to do this.

image
image
image

**Comment by SatoruUeda** [comment]
I can remove components and images that are not included in the page or screen after the download is complete.
I Implement if necessary.

**Comment by simonoliver** [comment]
Thanks for the updates - looks great! I'll try and review this week and get back to you shortly

**Comment by SatoruUeda** [comment]
Thank you.
No rush, please check back when you are available.

`https://github.com/simonoliver/UnityFigmaBridge/pull/19/commits/6da5726ed4c7ac5fce34015176f4b64cc7507ec7`

I've added code for removing unused objects on the page and screen.
I will revert if not needed.

**Comment by simonoliver** [comment]
Thanks - this looks great. I'm going to merge into a new branch in the repository before merging into main, I'll follow up with any changes that I'd suggest before merging

**Comment by SatoruUeda** [comment]
Thank you for contacting me!
I will confirm after the holiday.

**Comment by SatoruUeda** [comment]
@simonoliver 
> https://github.com/simonoliver/UnityFigmaBridge/tree/select_sync

I have checked this one.
I appreciate your many fixes.

I also understood that I will only select pages.

**Comment by simonoliver** [comment]
Thanks - I've just merged this into the main branch, really appreciate your help! Also I wanted to mention that autolayout is now off by default, but you can enable in the settings file.

**Pull request merged**
