### PR TITLE
Feature update prefab

### PR DESCRIPTION
**Pull request by InvivoLuke**
Ability to retain generated Prefabs from previous "Sync".
This allows us to create Prefab Variants that can retain changes with subsequent "Sync Document" actions, allowing us to make changes to both the Prefab Variant (development) and the Figma file (design and ux). This allows our workflow to have incremental changes as we continuously build the Figma Prototype into a Unity Application.

### CODE REVIEW

**Comment by InvivoLuke** [comment]
Thank you for developing the tool! We're using Figma in our organization and working on a workflow that works.. 
Do you have a feature roadmap in mind -- I'm sure there are features we can contribute towards as we continue to work on refining the workflow (and don't waste time duplicating the effort). Let us know!

**Comment by simonoliver** [comment]
Thanks, yeah any additional contributions would be very welcome. I do have a rough list of features that I'm considering but I'll try and transfer them to the repo's Issues so they are public.

I'm going to pull into a new branch and I'll let you know of any changes - I wonder whether there are any downsides to making this behaviour the default, rather than an option?

**Comment by simonoliver** [comment]
Hey - had a bit of a look at this and I'm getting some issues on a simple scene - https://www.figma.com/file/t9vhy9N9lqcsQit6XIyP4Z/Game-Jam-Template?type=design&node-id=1%3A2&mode=design&t=F8SHYlSi0P1Dix93-1

This seems to be thrown quite a few times:
"Issue saving prefab: System.ArgumentException: Calling apply or revert methods on an object which is not part of a Prefab instance is not supported."

Do you see the same on your side?

**Comment by simonoliver** [comment]
I'm seeing the buttons not appearing and if it's throwing an error this probably isn't going to be a workable solution for this  functionality.

I'm planning on implementing a future feature that will modify existing assets rather than replacing them (tracking changes between previous/last import of a figma file to detect changes) which will hopefully provide something similar. 

Thanks,
Simon

**Pull request merged**
